import pandas as pd
import os

class VerificationReport:
    def __init__(self, func_name, spss_out, r_out):
        self.func_name = func_name
        self.spss_df = pd.read_csv(spss_out)
        self.r_df = pd.read_csv(r_out)
        
    def generate_html(self, output_path):
        # 1. Calculate Summary Stats
        rows_spss = len(self.spss_df)
        rows_r = len(self.r_df)
        match = self.spss_df.equals(self.r_df)
        status = "✅ PASSED" if match else "❌ FAILED"
        color = "green" if match else "red"

        # 2. Sample Data Comparison (Top 5 rows)
        sample_html = self.spss_df.head(5).to_html(classes="table", index=False)

        html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: sans-serif; padding: 20px; }}
                .badge {{ background: {color}; color: white; padding: 10px; border-radius: 5px; font-weight: bold; }}
                .table {{ border-collapse: collapse; width: 100%; }}
                .table th, .table td {{ border: 1px solid #ddd; padding: 8px; }}
            </style>
        </head>
        <body>
            <h1>Migration Certificate: {self.func_name}</h1>
            <span class="badge">{status}</span>
            <hr>
            <h3>Summary</h3>
            <ul>
                <li><strong>Legacy Rows (SPSS):</strong> {rows_spss}</li>
                <li><strong>Modern Rows (R):</strong> {rows_r}</li>
            </ul>
            <h3>Data Sample (Verified Match)</h3>
            {sample_html}
            <hr>
            <p><em>Generated by Automated Equivalence Engine</em></p>
        </body>
        </html>
        """
        
        with open(output_path, 'w') as f:
            f.write(html)
        print(f"📄 Report generated: {output_path}")


        
